package:  simple_nav
version:  '1.5'
author:   Wolfgang Busch
supportpage: redaxo.org/support/community/

page:
    title: 'translate:simple_nav'
    perm:  admin[]
    icon:  rex-icon fa-align-left
    subpages:
        introduction: { title: 'translate:introduction' }
        description:  { title: 'translate:description' }
        handling:     { title: 'translate:handling' }
        example:      { title: 'translate:example'  }
        settings:     { title: 'translate:settings' }

requires:
    redaxo: ^5.3.0
